### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by RobertFischer** [Kaliber/play-s3#42]
https://github.com/Rhinofly/play-s3/blob/f612f542596056c6d709f5634f0009c69f1d209a/src/main/java/fly/play/s3/Bucket.scala#L251

From what I'm reading, it looks like we always have to buffer the entire file into memory before we can upload the file to S3. Is this correct, or am I missing an API?

**Comment by EECOLOR** [comment]
Did you manage to solve it? If so I would like to introduce the solution as a utility in the upcoming `6.0.0` release.

**Comment by neilchaudhuri** [comment]
Unfortunately, I was under time pressure to get the feature out and pursued an alternate course, so I wasn't able to figure anything out. Sorry about that.

If I get time to play around and come up with something that isn't terrible, I will let you know.

**Comment by EECOLOR** [comment]
I'm closing this for now.
