### ISSUE TITLE
rename has problem if more than one "directory" in destination path does not exist, returns NoSuchKey error

### ISSUE THREAD

**Issue by lutnos** [Kaliber/play-s3#48]
Hi again

I have found another problem using your rename.

I expect the cause is actually a weakness in the underlying AWS put copy using their X-Amz-copy-source header.

If I try to rename an object from say: d1/o1 to d2/o1, then the operation succeeds, even if there is nothing else with a d2 path.

However, if I try to rename an object from d1/o1 to d3/d4/o1, where no d3 path already exists, then it fails reporting NoSuchKey .

A spec for this would be something like:

    "be able to rename a file to another path" inApp {

      val result = testBucket rename("privateREADME.txt", "d1/private2README.txt", AUTHENTICATED_READ)
      noException(result)
    }

    "be able to rename a file to another path with two non-existent directory parts" inApp {

      val result = testBucket rename("privateREADME.txt", "d2/d3/private2README.txt", AUTHENTICATED_READ)
      noException(result)
    }

Where the first spec will pass but I expect the second spec will currently fail.

In my present application, I can work around this by always moving from d1/o1 to d3/o1 and then from d3/o1 to  d3/d4/o1 .  I can do that because I know d1/o1 will never otherwise exist. Were it not for that, I would be unsure just what to do, not seeing any other obvious way to the path without a terminal object.  Perhaps this is because I do not properly understand AWS' path & object abstraction.

All the best

**Comment by EECOLOR** [comment]
Thank you for reporting this.

On a quick glance I can not find anything about this in the documentation. As soon as I have time to work on this project I will investigate further. Any additional information is of course welcome.

**Comment by EECOLOR** [comment]
I could not reproduce the problem. I have added the suggested tests to the specification as seen in this commit: https://github.com/Kaliber/play-s3/commit/ccf16d77f6b95e7f88c9a09e2858b39168706d01

Please reopen the issue if you have more specific information that allows me to reproduce the issue.
