### ISSUE TITLE
Incompatibility with Play 2.5

### ISSUE THREAD

**Issue by neilchaudhuri** [Kaliber/play-s3#61]
Play 2.5 has changed the way they make REST calls, and it has broken play-s3 compatibility. Here is the error I get:

java.lang.ClassNotFoundException: com.ning.http.client.Response
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at fly.play.s3.Bucket.fly$play$s3$Bucket$$extractHeaders(Bucket.scala:226)
    at fly.play.s3.Bucket$$anonfun$get$1.apply(Bucket.scala:67)
    at fly.play.s3.Bucket$$anonfun$get$1.apply(Bucket.scala:66)
    at fly.play.aws.AwsResponse$.apply(AwsResponse.scala:8)

Please let me know if you intend to continue support for this library as Play evolves. They make a lot of changes even with minor versions, so I know it can be a lot to maintain.

Thanks.

**Comment by EECOLOR** [comment]
Yes, we plan to support it. Not sure when we will have modified the code to reflect the new changes.

The main body of work is with the streams: https://www.playframework.com/documentation/2.5.x/StreamsMigration25

And the other stuff seems to be just renaming.

**Comment by EECOLOR** [comment]
@Hayena has been working on this. He however had another project to focus his attention on. @Hayena , will you have time to work on this in the next week or so?

**Comment by Hayena** [comment]
I will see if I have time tonight to finish this otherwise I'll do it this weekend

**Comment by EECOLOR** [comment]
Apart from a single failing test it seems the 2.5 branch is functioning (see https://github.com/Kaliber/play-s3/pull/62 for details). As soon as I have some more time I will release it.

**Comment by EECOLOR** [comment]
Release `8.0.0` supports Play 2.5

**Comment by neilchaudhuri** [comment]
In order to initialize an S3 instance with S3(bucketName) in the README and tests, you import play.api.Play.current, which is a static reference to Application. This is deprecated.

As described in the [documentation](https://www.playframework.com/documentation/2.5.x/Migration25), the tests should reflect how to use dependency injection to provide the Application. Or possibly take a different approach entirely. Either way, the tests and documentation should reflect the preferred approach.

**Comment by EECOLOR** [comment]
Very good point, I totally forgot about that part of the library. As soon as I have a chance, I will fix it. Here we only use the [compile time dependency injection](https://www.playframework.com/documentation/2.5.x/ScalaCompileTimeDependencyInjection) approach in combination with the following signature:

```
def fromConfiguration(client: WSClient, configuration: Configuration)
```

We should probably add some annotations that help with the Guice version. I however have no direct experience with that. I might add another ticket and accept pull requests on that one.

In any case, as soon as I have time I will update the documentation and tests. Any help with that is of course appreciated.

**Comment by GitsMcGee** [comment]
People using Guice can inject the Application and put it into implicit scope, and everything works great. Injecting the Application, however is considered to be a big no no, since it creates circular dependencies (Application depends on the controllers, which depend on everything else, so having something depend on Application completes the circle). 

A quick fix could be to simply deprecate the `def apply(...)(implicit app: Application)` methods, and replace them with `def apply(...)(implicit client: WSClient, configuration: Configuration)` methods instead.

**Comment by EECOLOR** [comment]
@GitsMcGee agreed. As you might have noticed, my time has been very limited the last few months. If you feel this is very important please create a pull request.

**Comment by GitsMcGee** [comment]
@EECOLOR Sounds good. I wouldn't say it's hugely important, but it would certainly be nice to have. I'll make a pull request as soon as I have the time.

**Comment by thehappycoder** [comment]
Just got this with play-2.5 and play-s3-8.0.0:
```
Tried proxying play.api.Application to support a circular dependency, but circular proxies are disabled
```

Replacing implicit Application with implicit client: WSClient, configuration: Configuration didn't help.

**Comment by EECOLOR** [comment]
@thehappycoder I don't see how this library can cause that problem. Could you maybe create a minimal example that reproduces the problem?

**Comment by EECOLOR** [comment]
@thehappycoder oh and feel free to create a new issue

**Comment by thehappycoder** [comment]
@EECOLOR All good. I had a mistake in code.

**Comment by ceecer1** [comment]
@EECOLOR  I tried to upload a file in S3 bucket using this library, but I see some strange error as below. I searched a bit about the originalUri in the error but could not find any clues.

I am using play 2.5, and using the following snippet to get the bucket.
lazy val s3 = S3.fromConfiguration(ws, configuration)
lazy val bucket = s3.getBucket(configuration.getString("s3.bucket").get)


play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: orginalUri]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
Caused by: java.lang.NullPointerException: orginalUri
	at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
	at org.asynchttpclient.uri.UriParser.parse(UriParser.java:320)
	at org.asynchttpclient.uri.Uri.create(Uri.java:36)
	at org.asynchttpclient.netty.handler.intercept.Redirect30xInterceptor.exitAfterHandlingRedirect(Redirect30xInterceptor.java:123)
	at org.asynchttpclient.netty.handler.intercept.Interceptors.exitAfterIntercept(Interceptors.java:86)
	at org.asynchttpclient.netty.handler.HttpHandler.handleHttpResponse(HttpHandler.java:130)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:186)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)


Please let me know if there is anyway to tackle this issue. Any help would be greatly appreciated.

Thanks

**Comment by thehappycoder** [comment]
@ceecer1 Make sure you have region defined in s3.region configuration prop and make sure you define bucket name. It happened to me in both of these cases.

**Comment by ceecer1** [comment]
@thehappycoder Thanks it worked, my bucket didn't require a s3 region.

**Comment by git4sun** [comment]
@thehappycoder I have the same issue. But I did set s3.region. Where do I define the bucket name except according to the readme: `val bucket = S3("mybucket")`?

**Comment by EECOLOR** [comment]
@git4sun can you post the error (including the stacktrace)?

**Comment by git4sun** [comment]
[debug] o.a.n.c.ChannelManager - Closing Channel [id: 0xa7f09993, L:/192.168.4.xx:55153 - R:s3-us-west-2.amazonaws.com/54.231.185.xx:443] [debug] i.n.h.l.LoggingHandler - [id: 0xa7f09993, L:/192.168.4.xx:55153 - R:s3-us-west-2.amazonaws.com/54.231.185.xx:443] CLOSE() [debug] o.a.n.r.NettyRequestSender - Aborting Future NettyResponseFuture{currentRetry=0, isDone=false, isCancelled=false, asyncHandler=play.api.libs.ws.ahc.AhcWSRequest$$anon$1@1d3f666c, nettyRequest=org.asynchttpclient.netty.request.NettyRequest@4a7e4d5d, content=null, uri=https://s3-us-west-2.amazonaws.com/mybucket/requestBody7117625290787684978asTemporaryFile, keepAlive=false, exEx=null, redirectCount=1, timeoutsHolder=org.asynchttpclient.netty.timeout.TimeoutsHolder@f298834, inAuth=false, statusReceived=false, touch=1473749356653} [debug] o.a.n.r.NettyRequestSender - orginalUri java.lang.NullPointerException: orginalUri at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23) at org.asynchttpclient.uri.UriParser.parse(UriParser.java:320) at org.asynchttpclient.uri.Uri.create(Uri.java:36) at org.asynchttpclient.netty.handler.intercept.Redirect30xInterceptor.exitAfterHandlingRedirect(Redirect30xInterceptor.java:123) at org.asynchttpclient.netty.handler.intercept.Interceptors.exitAfterIntercept(Interceptors.java:86) at org.asynchttpclient.netty.handler.HttpHandler.handleHttpResponse(HttpHandler.java:130) at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:186) at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [debug] o.a.n.c.ChannelManager - Closing Channel [id: 0xa7f09993, L:/192.168.4.xx:55153 ! R:s3-us-west-2.amazonaws.com/54.231.185.xx:443] [debug] o.a.n.h.HttpHandler - Unexpected I/O exception on channel [id: 0xa7f09993, L:/192.168.4.95:55153 ! R:s3-us-west-2.amazonaws.com/54.231.185.24:443] java.lang.NullPointerException: orginalUri at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23) at org.asynchttpclient.uri.UriParser.parse(UriParser.java:320) at org.asynchttpclient.uri.Uri.create(Uri.java:36) at org.asynchttpclient.netty.handler.intercept.Redirect30xInterceptor.exitAfterHandlingRedirect(Redirect30xInterceptor.java:123) at org.asynchttpclient.netty.handler.intercept.Interceptors.exitAfterIntercept(Interceptors.java:86) at org.asynchttpclient.netty.handler.HttpHandler.handleHttpResponse(HttpHandler.java:130) at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:186) at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [debug] o.a.n.c.ChannelManager - Closing Channel [id: 0xa7f09993, L:/192.168.4.xx:55153 ! R:s3-us-west-2.amazonaws.com/54.231.185.xx:443] [debug] i.n.h.l.LoggingHandler - [id: 0xa7f09993, L:/192.168.4.xx:55153 ! R:s3-us-west-2.amazonaws.com/54.231.185.xx:443] INACTIVE [debug] o.a.n.h.HttpHandler - Channel Closed: [id: 0xa7f09993, L:/192.168.4.xx:55153 ! R:s3-us-west-2.amazonaws.com/54.231.185.xx:443] with attribute INSTANCE [debug] i.n.h.l.LoggingHandler - [id: 0xa7f09993, L:/192.168.4.xx:55153 ! R:s3-us-west-2.amazonaws.com/54.231.185.xx:443] UNREGISTERED [debug] o.a.n.c.DefaultChannelPool - Closed 0 connections out of 0 in 0ms

**Comment by EECOLOR** [comment]
Does calling `bucket.url("test", 1)` give you the same error?

**Comment by git4sun** [comment]
no. The error is caused by this line: `val result = bucket + BucketFile(file.getName, request.headers.get("Content-Type").get, byteArray, None, None)`. More specifically, the `+` causes the error. It seems that the error happened only when actually communicating with S3 server.

**Comment by EECOLOR** [comment]
What is the output of `bucket.url("test", 1)`

**Comment by git4sun** [comment]
https://s3-us-west-2.amazonaws.com/mybucket/test?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature={somestring}&X-Amz-Date=20160913T094502Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1&X-Amz-Credential={mykey}%2F20160913%2Fus-west-2%2Fs3%2Faws4_request"

**Comment by EECOLOR** [comment]
@git4sun That url already shows the problem. Amazon is responding with a `301`, but without a `location` header. The netty code does not expect this:

```
String location = responseHeaders.get(HttpHeaders.Names.LOCATION);
Uri newUri = Uri.create(future.getUri(), location);
```

And the `parse` function throws a very cryptic error: `assertNotNull(originalUrl, "orginalUri");`

The body of the response of the url you provided contains some clues:

> The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

From what I can tell this means that the bucket was created in a region that is not `us-west-2`.

**Comment by git4sun** [comment]
@EECOLOR thanks.
